export const DEFAULT_STARTING_POINT_NUMBER = 5;
export const DEFAULT_MAP_SIZE_SMALL = 10;
export const DEFAULT_MAP_SIZE_MEDIUM = 15;
export const DEFAULT_STARTING_COUNTER_TWO = 2;
export const DEFAULT_STARTING_COUNTER_FOUR = 4;
export const DEFAULT_STARTING_COUNTER_SIX = 6;
export const DEFAULT_STARTING_COUNTER_ONE = 1;
